USE a9763_Main;

CREATE TABLE USR (
    USRID INT,
    USRN VARCHAR(256) UNIQUE,
    USRPSW CHAR(128),
    PRIMARY KEY (USRID)
);

CREATE TABLE USRTOKENS (
    USRID INT,
    TOKEN CHAR(128) UNIQUE,
	TOD TIMESTAMP,
    PRIMARY KEY (USRID),
    FOREIGN KEY (USRID) REFERENCES USR(USRID)
);


DELIMITER $
CREATE PROCEDURE ADD_USR
(IN PUSRN VARCHAR(256), IN PUSRPSW VARCHAR(128))
BEGIN
    SET @TEMPUSRN = NULL;
    SELECT USRN INTO @TEMPUSRN FROM USR WHERE USRN = PUSRN;
    IF @TEMPUSRN IS NULL THEN
    SET @TEMPUSRID = NULL;
    SELECT MAX(USRID) INTO @TEMPUSRID FROM USR;
    IF @TEMPUSRID IS NULL THEN
    SET @TEMPUSRID = 1;
    ELSE
    SET @TEMPUSRID = @TEMPUSRID + 1;
    END IF;
    INSERT INTO USR (USRID, USRN, USRPSW) VALUES (@TEMPUSRID, PUSRN, SHA2(PUSRPSW,512));
    SELECT 'USER ADDED' AS MSG;
    ELSE
    SELECT 'ERROR UNABLE TO ADD USER' AS MSG;
    END IF;
END
$

CREATE PROCEDURE  VALIDATE_USR
(IN PUSRN VARCHAR(256), IN PUSRPSW VARCHAR(128))
BEGIN
    SET @VALID = 0;
    SELECT 1 INTO @VALID FROM USR WHERE USRN = PUSRN AND USRPSW = SHA2(PUSRPSW,512);
    SELECT @VALID AS VALID;
END
$

CREATE PROCEDURE  LOGIN_USR
(IN PUSRN VARCHAR(256), IN PUSRPSW VARCHAR(128))
BEGIN
    SET @TEMPUSRID = NULL;
    SELECT USRID INTO @TEMPUSRID FROM USR WHERE USRN = PUSRN AND USRPSW = SHA2(PUSRPSW,512);
    IF @TEMPUSRID IS NOT NULL THEN
    SET @TOKEN = SHA2(CONCAT(RAND(),':',@TEMPUSRID),512);
    SET @T = NULL;
    SELECT TOKEN INTO @T FROM USRTOKENS WHERE USRID = @TEMPUSRID;
    IF @T IS NULL THEN
    INSERT INTO USRTOKENS (USRID, TOKEN, TOD) VALUES (@TEMPUSRID, @TOKEN, TIMESTAMPADD(HOUR, 2, CURRENT_TIMESTAMP()));
    ELSE
    UPDATE USRTOKENS SET TOKEN = @TOKEN, TOD = TIMESTAMPADD(HOUR, 2, CURRENT_TIMESTAMP()) WHERE USRID = @TEMPUSRID;
    END IF;
    SELECT @TOKEN AS TOKEN;
    ELSE
    SELECT 'ERROR' AS TOKEN;
    END IF;
END
$

CREATE PROCEDURE  VALIDATE_USRTOKENS
(IN PTOKEN CHAR(128))
BEGIN
    SET @USRID = NULL;
	SET @TOD = NULL;
    SELECT USRID, TOD INTO @USRID, @TOD FROM USRTOKENS WHERE TOKEN = PTOKEN;
    SELECT USRN, UNIX_TIMESTAMP(@TOD) AS TOD FROM USR WHERE USRID = @USRID;
END
$
